[build]
  builder = "nixpacks"
  buildCommand = "clojure -P && pip3 install --break-system-packages 'httpx[http2]' pydantic tenacity"

[deploy]
  numReplicas = 1
  startCommand = "clojure -M:bot"
  healthcheckPath = "/"
  restartPolicyType = "always"
